### ISSUE TITLE
Pin nix pkgs to a hash

### ISSUE THREAD

**Issue by Fresheyeball** [hasktorch/hasktorch#143] opened 2019-02-03 19:26 UTC
#103 

Is really not complete. 
https://github.com/hasktorch/hasktorch/blob/master/shell.nix#L5
https://github.com/hasktorch/hasktorch/blob/master/build.nix#L49

Both use `<nixpkgs>` and as a result, the project does not rebuild reproducibility. I spent some time trying to get a hash that will build Aten, but failed. Please pin to a specific rev of nixpkgs, such that the project can build.

**Comment by stites** [comment] 2019-02-04 21:37
:+1:

I was trying to fix the GPU-nix scripts in https://github.com/hasktorch/hasktorch/pull/141 and had to work through a few kinks that would have been solved with this. Thanks for the catch! I'm pretty sure the gcc workarounds in there apply to the CPU build, so this may address your issues. Unfortunately, I've never been able to get these GPU-nix scripts working which means that I've mostly neglected them.

The CPU side of this PR should be working as of 7 days ago -- I'll verify once again and pin everything this week.

**Comment by stites** [comment] 2019-02-06 16:55
Addressed in https://github.com/hasktorch/hasktorch/pull/141/commits/94ff279b7b52fe6abe5bc24fcaaf633f977fbbce

**Comment by Fresheyeball** [comment] 2019-02-23 03:24
`nix-build`

```
these derivations will be built:
  /nix/store/45xpn4q9abgyqz1qkfac318n7i4ksi30-magma-2.4.0.tar.gz.drv
  /nix/store/gnk70yal26na0365hj44mkb9skpzgl2i-hasktorch-types-thc-0.0.1.0.drv
  /nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv
  /nix/store/l3ydlkagsjkjj4insqgkk1fsrrrl51sv-hasktorch-ffi-th-0.0.1.0.drv
  /nix/store/pwr7p86f05s2x1f2f445mr8pkflv7d14-gfortran-gcc5-wrapper-5.5.0.drv
  /nix/store/rnvkjb85v6rvpkg453054p5yyq0hy3cm-magma-2.4.0.drv
  /nix/store/x5yl2sxsqig04zvz53j21acvff1hqpad-nvidia-x11-410.66-4.19.drv
these paths will be fetched (70.34 MiB download, 159.72 MiB unpacked):
  /nix/store/i87344774bshyf1ccxak4llrdyg65k45-libpthread-stubs-0.4
  /nix/store/j28aaxsp1cggbd4d4fqv9lmzphm2r2ni-linux-4.19-dev
  /nix/store/wq4xlc49v3wrgvyibik82bkf9c8jv42r-linux-4.19
copying path '/nix/store/i87344774bshyf1ccxak4llrdyg65k45-libpthread-stubs-0.4' from 'https://cache.nixos.org'...
building '/nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv'...
building '/nix/store/gnk70yal26na0365hj44mkb9skpzgl2i-hasktorch-types-thc-0.0.1.0.drv'...
copying path '/nix/store/wq4xlc49v3wrgvyibik82bkf9c8jv42r-linux-4.19' from 'https://cache.nixos.org'...
building '/nix/store/pwr7p86f05s2x1f2f445mr8pkflv7d14-gfortran-gcc5-wrapper-5.5.0.drv'...
building '/nix/store/45xpn4q9abgyqz1qkfac318n7i4ksi30-magma-2.4.0.tar.gz.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
'/nix/store/bzhyjp73zw60fx8461q7y2dnjwwvrw78-gfortran-gcc5-wrapper-5.5.0/bin/g77' -> 'gfortran'
'/nix/store/bzhyjp73zw60fx8461q7y2dnjwwvrw78-gfortran-gcc5-wrapper-5.5.0/bin/f77' -> 'gfortran'
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/bzhyjp73zw60fx8461q7y2dnjwwvrw78-gfortran-gcc5-wrapper-5.5.0
patching script interpreter paths in /nix/store/bzhyjp73zw60fx8461q7y2dnjwwvrw78-gfortran-gcc5-wrapper-5.5.0
checking for references to /build/ in /nix/store/bzhyjp73zw60fx8461q7y2dnjwwvrw78-gfortran-gcc5-wrapper-5.5.0...
unpacking sources
unpacking source archive /nix/store/izghgrsmd37llaslh4jabd9smpcsz38b-aten
source root is aten
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten/include -DCMAKE_INSTALL_LIBDIR=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten/lib -DCMAKE_INSTALL_NAME_DIR=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/strip -DCMAKE_RANLIB=/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/ranlib -DCMAKE_AR=/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten -DNO_CUDA=true -Wno-dev
CMake Error: The source directory "/build/aten" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
builder for '/nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv' failed with exit code 1
error: build of '/nix/store/gnk70yal26na0365hj44mkb9skpzgl2i-hasktorch-types-thc-0.0.1.0.drv', '/nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv', '/nix/store/l3ydlkagsjkjj4insqgkk1fsrrrl51sv-hasktorch-ffi-th-0.0.1.0.drv', '/nix/store/rnvkjb85v6rvpkg453054p5yyq0hy3cm-magma-2.4.0.drv', '/nix/store/x5yl2sxsqig04zvz53j21acvff1hqpad-nvidia-x11-410.66-4.19.drv' failed
```

`nix-shell`
```
these derivations will be built:
  /nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv
  /nix/store/kymprb5yzj6bwm0lyy5v2naqvaz5gyv7-linux-4.19.drv
  /nix/store/l3ydlkagsjkjj4insqgkk1fsrrrl51sv-hasktorch-ffi-th-0.0.1.0.drv
  /nix/store/ydq26k3wmjnndbbn7jlwz3b2bwn4wrd6-nvidia-x11-410.66-4.19.drv
building '/nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv'...
building '/nix/store/kymprb5yzj6bwm0lyy5v2naqvaz5gyv7-linux-4.19.drv'...
unpacking sources
unpacking source archive /nix/store/izghgrsmd37llaslh4jabd9smpcsz38b-aten
source root is aten
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten/include -DCMAKE_INSTALL_LIBDIR=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten/lib -DCMAKE_INSTALL_NAME_DIR=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/strip -DCMAKE_RANLIB=/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/ranlib -DCMAKE_AR=/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/1wawgkww6gw6virq2s4cjiwsp3yn8pnn-hasktorch-aten -DNO_CUDA=true -Wno-dev
CMake Error: The source directory "/build/aten" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
builder for '/nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv' failed with exit code 1
error: build of '/nix/store/ihs8nnb12d0v2xvfi2hdjz81xa6r256k-hasktorch-aten.drv', '/nix/store/l3ydlkagsjkjj4insqgkk1fsrrrl51sv-hasktorch-ffi-th-0.0.1.0.drv', '/nix/store/ydq26k3wmjnndbbn7jlwz3b2bwn4wrd6-nvidia-x11-410.66-4.19.drv' failed
```

**Comment by stites** [comment] 2019-02-25 02:06
Cool -- I'll check it out.

**Comment by bmabsout** [comment] 2019-04-15 00:10
Calling make init then nix-shell solved that issue for me.

**Comment by stites** [comment] 2019-04-17 22:20
@bmabsout @Fresheyeball -- personally, I think you should postpone nix support until the libtorch-1.x support that @junjihashimoto is working on (taking place in hasktorch/ffi-experimental). This is much easier to build and works (when builing C++ projects with cmake) here: https://github.com/stites/libtorch-nix

I'm currently working on breaking the cmake dependency and should have something running soon (help would be appreciated and the build is much faster : P). There's an outstanding question of how this library integrates with `nixpkgs.pytorch`, but I'm not primarily concerned with python and the cmake scripts seem simple enough.

**Comment by tscholak** [comment] 2019-06-10 12:07
@stites can you give a quick update on this if you have the chance? thanks
I could help if I’m shown where the problem is

**Comment by stites** [comment] 2019-06-11 11:35
@tscholak - currently traveling without a laptop, perhaps you (and other folks) should ping me/@austinvhuang/junji(mobile doesn't auto-fill names) on gitter or keybase to get access to the slack channel.

The nix scripts here become trivial once we get ffi-experimental in. I have a repo that pulls down libtorch and runs some C++, but I think the more comprehensive thing to do is output lib/include folders from the pytorch derivation (which still hasn't gotten the 1.1.0 bump, I don't think).

**Comment by stites** [comment] 2019-08-04 15:48
ffi-experimental is in master, and it doesn't actively support a nix workflow. [pytorch-world](https://github.com/stites/pytorch-world) (which I've renamed from "libtorch-nix") will be the best place to go to iterate on nix-support. It's also where I've been working on the [pytorch-1.1.0 derivation](https://github.com/NixOS/nixpkgs/pull/65041) -- which works without FBGEMM, and might turn into a 1.1.1 derivation.

If you'd like to work on hasktorch with nix, please help out on that repo (which is properly pinned, following lorri's style). https://github.com/stites/pytorch-world/issues/2 blocks a cmake-less libtorch (which is nessecary for hasktorch), @tscholak has also been helping test that repo on darwin.

If someone starts working on nix support and needs a pin, please pull in pytorch-world as a submodule in a `nix` folder (so `<hasktorch_root>/nix`) and use the pin located at `<hasktorch_root>/nix/pin`.

Refer to https://github.com/stites/probtorch/tree/nix as an example.

**Closed** 2019-08-04 15:49 UTC
